"""Report writers for AigenGuard."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


SECTION_DESCRIPTIONS = {
    "Models": "Model identifiers found in code or configuration.",
    "Providers": "AI providers or SDKs referenced by the repository.",
    "Frameworks": (
        "Agent orchestration libraries that may route prompts, tools, memory, or callbacks."
    ),
    "MCP Security Analysis": (
        "MCP inventory from local JSON configuration. Reachable exposure is reported "
        "separately when static agent, framework, or prompt evidence supports it."
    ),
    "Prompt Files": "Prompt and instruction files that can influence agent behavior.",
    "Capabilities": (
        "Static evidence of sensitive actions such as shell, network, database, "
        "cloud, or code execution."
    ),
    "Dependencies": "AI, MCP, or sandbox-related dependencies found in package manifests.",
    "Secret References": (
        "Credential names referenced by the repository. AigenGuard records names "
        "only, never values."
    ),
    "Secret Leak Findings": (
        "Likely AI/API credential values found by deterministic static checks. "
        "Values are always redacted."
    ),
    "Risks": (
        "Scanner-level review signals derived from the findings above. "
        "They are not exploit claims."
    ),
}


def write_reports(
    bom: dict[str, Any], output_dir: str | Path, pretty: bool = False
) -> tuple[Path, Path]:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    json_path = out / "agentbom.json"
    md_path = out / "agentbom.md"

    indent = 2 if pretty else None
    json_path.write_text(json.dumps(bom, indent=indent, sort_keys=pretty) + "\n", encoding="utf-8")
    md_path.write_text(render_markdown(bom), encoding="utf-8")
    return json_path, md_path


def render_markdown(bom: dict[str, Any]) -> str:
    lines = [
        "# AigenGuard",
        "",
        f"- Schema version: {bom['schema_version']}",
        f"- Repository: {bom['repository']}",
        f"- Generated by: {bom['generated_by']}",
        "",
    ]

    lines.extend(_reader_guide_section())
    lines.extend(_repository_risk_section(bom.get("repository_risk", {})))
    lines.extend(_diff_section(bom.get("diff", {})))
    lines.extend(_policy_review_section(bom.get("policy_review")))
    lines.extend(_review_priorities_section(bom))
    lines.extend(_reachable_capability_section(bom.get("reachable_capabilities", [])))
    lines.extend(_policy_finding_section(bom.get("policy_findings", [])))
    lines.extend(_model_section(bom.get("models", [])))
    lines.extend(_section("Providers", bom.get("providers", bom.get("models", []))))
    lines.extend(_section("Frameworks", bom["frameworks"]))
    lines.extend(_mcp_security_section(bom.get("mcp_servers", [])))
    lines.extend(_section("Prompt Files", bom["prompts"]))
    lines.extend(_section("Capabilities", bom["capabilities"]))
    lines.extend(_dependency_section(bom.get("dependencies", [])))
    lines.extend(_section("Secret References", bom["secret_references"]))
    lines.extend(_secret_leak_section(bom.get("secret_leak_findings", [])))
    lines.extend(_risk_section(bom["risks"]))
    return "\n".join(lines).rstrip() + "\n"


def _reader_guide_section() -> list[str]:
    return [
        "## How to read this report",
        "",
        "AigenGuard is an offline static scanner. It does not prove exploitability.",
        "",
        "Start with repository risk, review priorities, reachable capabilities, "
        "and policy findings. Then use the component sections to confirm source files.",
        "",
    ]


def _review_priorities_section(bom: dict[str, Any]) -> list[str]:
    priorities = _review_priorities(bom)
    lines = ["## Review Priorities", ""]
    if not priorities:
        lines.extend(["No immediate review priorities detected.", ""])
        return lines
    for priority in priorities:
        lines.append(f"- {priority}")
    lines.append("")
    return lines


def _review_priorities(bom: dict[str, Any]) -> list[str]:
    priorities: list[str] = []
    for item in bom.get("reachable_capabilities", []):
        if not isinstance(item, dict):
            continue
        if item.get("risk") == "high":
            priorities.append(
                "Review reachable {capability} from {reachable_from} in {source_file}.".format(
                    capability=item.get("capability", "capability"),
                    reachable_from=item.get("reachable_from", "agent actor"),
                    source_file=item.get("source_file", "unknown file"),
                )
            )
    for item in bom.get("policy_findings", []):
        if not isinstance(item, dict):
            continue
        if item.get("severity") in {"critical", "high", "medium"}:
            priorities.append(
                "Address policy finding in {source_file}: {message}.".format(
                    source_file=item.get("source_file", "unknown file"),
                    message=item.get("message", "policy control needed"),
                )
            )
    if bom.get("secret_references"):
        priorities.append("Confirm referenced credentials are stored outside the repository.")
    if bom.get("secret_leak_findings"):
        priorities.append("Remove leaked credential values from the repository and rotate them.")
    return priorities[:5]


def _section(title: str, items: list[dict[str, str]]) -> list[str]:
    lines = [f"## {title}", ""]
    if title in SECTION_DESCRIPTIONS:
        lines.extend([SECTION_DESCRIPTIONS[title], ""])
    if not items:
        lines.extend(["None detected.", ""])
        return lines
    for item in items:
        label = item.get("name") or item.get("path") or item.get("type", "item")
        path = item.get("path")
        confidence = item.get("confidence")
        policy_status = _policy_status_label(item.get("policy_status"))
        detail = f" ({path})" if path and path != label else ""
        if confidence:
            detail += f" [confidence: {confidence}]"
        if policy_status:
            detail += f" [Policy status: {policy_status}]"
        lines.append(f"- {label}{detail}")
    lines.append("")
    return lines


def _model_section(items: list[dict[str, str]]) -> list[str]:
    lines = ["## Models", ""]
    lines.extend([SECTION_DESCRIPTIONS["Models"], ""])
    if not items:
        lines.extend(["None detected.", ""])
        return lines
    for item in items:
        name = item.get("name", "model")
        source_file = item.get("source_file")
        confidence = item.get("confidence")
        detail = f" ({source_file})" if source_file else ""
        if confidence:
            detail += f" [confidence: {confidence}]"
        lines.append(f"- {name}{detail}")
    lines.append("")
    return lines


def _reachable_capability_section(items: list[dict[str, str]]) -> list[str]:
    lines = ["## Reachable Capabilities", ""]
    lines.extend(
        [
            "Deterministic actor-to-capability relationships where static evidence "
            "suggests an AI component may be able to use a sensitive action or "
            "configured MCP server. AigenGuard does not execute MCP servers and "
            "does not prove runtime reachability.",
            "",
        ]
    )
    if not items:
        lines.extend(["None detected.", ""])
        return lines
    for item in items:
        paths = item.get("paths", [])
        path_detail = f"; paths: {', '.join(paths)}" if isinstance(paths, list) and paths else ""
        server = item.get("mcp_server")
        server_detail = f"; MCP server: {server}" if server else ""
        mitigations = item.get("mitigations", [])
        mitigation_detail = ""
        if isinstance(mitigations, list) and mitigations:
            mitigation_detail = f"; mitigations: {', '.join(str(value) for value in mitigations)}"
        rationale = item.get("rationale", [])
        rationale_detail = ""
        if isinstance(rationale, list) and rationale:
            rationale_detail = f"; rationale: {'; '.join(str(reason) for reason in rationale)}"
        score = item.get("confidence_score")
        score_detail = f"; score: {score}" if score is not None else ""
        policy_status = _policy_status_label(item.get("policy_status"))
        policy_detail = f"; Policy status: {policy_status}" if policy_status else ""
        detail = (
            "[risk: {risk}; confidence: {confidence}{score_detail}"
            "{path_detail}{server_detail}{mitigation_detail}{rationale_detail}"
            "{policy_detail}]"
        ).format(
            score_detail=score_detail,
            path_detail=path_detail,
            server_detail=server_detail,
            mitigation_detail=mitigation_detail,
            rationale_detail=rationale_detail,
            policy_detail=policy_detail,
            **item,
        )
        lines.append(
            "- {capability} from {reachable_from} ({source_file}) {detail}".format(
                detail=detail, **item
            )
        )
    lines.append("")
    return lines


def _mcp_security_section(items: list[dict[str, object]]) -> list[str]:
    lines = ["## MCP Security Analysis", ""]
    lines.extend([SECTION_DESCRIPTIONS["MCP Security Analysis"], ""])
    if not items:
        lines.extend(["None detected.", ""])
        return lines
    for item in items:
        name = str(item.get("name", "mcp"))
        path = str(item.get("path", ""))
        confidence = str(item.get("confidence", ""))
        risk = str(item.get("risk", "low"))
        status = str(item.get("parse_status", "detected"))
        categories = item.get("risk_categories", [])
        category_detail = ""
        if isinstance(categories, list) and categories:
            category_detail = f"; categories: {', '.join(str(category) for category in categories)}"
        metadata = _mcp_metadata(item)
        rationale = item.get("rationale", [])
        rationale_detail = ""
        if isinstance(rationale, list) and rationale:
            rationale_detail = f"; rationale: {'; '.join(str(reason) for reason in rationale)}"
        policy_status = _policy_status_label(item.get("policy_status"))
        policy_detail = f"; Policy status: {policy_status}" if policy_status else ""
        detail = (
            f"[risk: {risk}; confidence: {confidence}; status: {status}"
            f"{category_detail}{metadata}{rationale_detail}{policy_detail}]"
        )
        lines.append(
            f"- {name} ({path}) {detail}"
        )
    lines.append("")
    return lines


def _mcp_metadata(item: dict[str, object]) -> str:
    parts = []
    for key, label in (
        ("command", "command"),
        ("package", "package"),
        ("transport", "transport"),
    ):
        value = item.get(key)
        if isinstance(value, str) and value:
            parts.append(f"{label}: {value}")
    args = item.get("args")
    if isinstance(args, list) and args:
        parts.append(f"args: {' '.join(str(arg) for arg in args)}")
    env = item.get("env")
    if isinstance(env, list) and env:
        parts.append(f"env: {', '.join(str(name) for name in env)}")
    return f"; {'; '.join(parts)}" if parts else ""


def _dependency_section(items: list[dict[str, str]]) -> list[str]:
    lines = ["## Dependencies", ""]
    lines.extend([SECTION_DESCRIPTIONS["Dependencies"], ""])
    if not items:
        lines.extend(["None detected.", ""])
        return lines
    for item in items:
        lines.append(
            "- {name} [category: {category}; path: {path}; confidence: {confidence}]".format(
                **item
            )
        )
    lines.append("")
    return lines


def _secret_leak_section(items: object) -> list[str]:
    lines = ["## Secret Leak Findings", ""]
    lines.extend([SECTION_DESCRIPTIONS["Secret Leak Findings"], ""])
    findings = _finding_list(items)
    if not findings:
        lines.extend(["None detected.", ""])
        return lines
    for item in findings:
        location = str(item.get("path", ""))
        line = item.get("line")
        if isinstance(line, int):
            location = f"{location}:{line}" if location else str(line)
        lines.append(
            "- {severity}: {title} ({location}) "
            "[confidence: {confidence}; evidence: {evidence}]".format(
                severity=item.get("severity", "high"),
                title=item.get("title", "Possible secret value"),
                location=location,
                confidence=item.get("confidence", "medium"),
                evidence=item.get("redacted_evidence", "[REDACTED]"),
            )
        )
    lines.append("")
    return lines


def _policy_finding_section(items: list[dict[str, str]]) -> list[str]:
    lines = ["## Policy Findings", ""]
    lines.extend(
        [
            "Controls that appear missing or violated based on prompts, "
            "capabilities, MCP configuration, and custom policy.",
            "",
        ]
    )
    if not items:
        lines.extend(["None detected.", ""])
        return lines
    for item in items:
        policy_status = _policy_status_label(item.get("policy_status"))
        policy_detail = f" [Policy status: {policy_status}]" if policy_status else ""
        lines.append(
            f"- {item['severity']}: {item['message']} "
            f"({item['source_file']}){policy_detail}"
        )
    lines.append("")
    return lines


def _repository_risk_section(item: dict[str, Any]) -> list[str]:
    lines = ["## Repository Risk", ""]
    lines.extend(
        [
            "A compact review score derived from reachable capabilities, "
            "sensitive actions, credential references, and policy gaps.",
            "",
        ]
    )
    score = item.get("score", 0)
    severity = item.get("severity", "low")
    lines.append(f"- Score: {score}")
    lines.append(f"- Severity: {severity}")
    rationale = item.get("rationale", [])
    if isinstance(rationale, list) and rationale:
        lines.append("- Rationale:")
        for reason in rationale:
            lines.append(f"  - {reason}")
    lines.append("")
    return lines


def _diff_section(diff: object) -> list[str]:
    if not isinstance(diff, dict) or not diff:
        return []
    lines = ["## Changes since baseline", ""]
    lines.extend(
        [
            "Comparison against the supplied baseline report. Finding IDs are stable "
            "for the same normalized finding identity.",
            "",
        ]
    )
    lines.extend(
        [
            "| Status | Count |",
            "| --- | ---: |",
            f"| Introduced | {len(_list(diff.get('introduced')))} |",
            f"| Resolved | {len(_list(diff.get('resolved')))} |",
            f"| Unchanged | {len(_list(diff.get('unchanged')))} |",
            "",
        ]
    )
    for key, title in (
        ("introduced", "Introduced Findings"),
        ("resolved", "Resolved Findings"),
        ("unchanged", "Unchanged Findings"),
    ):
        items = diff.get(key, [])
        lines.extend([f"### {title}", ""])
        if not isinstance(items, list) or not items:
            lines.extend(["None.", ""])
            continue
        for item in items:
            if not isinstance(item, dict):
                continue
            source = item.get("source_file", "")
            source_detail = f" ({source})" if source else ""
            lines.append(
                "- {severity}: {category} {title}{source_detail} [{id}]".format(
                    severity=item.get("severity", "low"),
                    category=item.get("category", "finding"),
                    title=item.get("title", "finding"),
                    source_detail=source_detail,
                    id=item.get("id", ""),
                )
            )
        lines.append("")
    return lines


def _policy_review_section(policy_review: object) -> list[str]:
    if not isinstance(policy_review, dict):
        return []
    status = _policy_review_status(policy_review)
    mode = policy_review.get("mode", "advisory")
    lines = [
        "## Policy review",
        "",
        f"Status: {status}",
        f"Mode: {mode}",
    ]
    policy_file = policy_review.get("policy_file")
    if policy_file:
        lines.append(f"Policy file: {policy_file}")
    lines.append("")

    violations = _finding_list(policy_review.get("violations"))
    warnings = _finding_list(policy_review.get("warnings"))
    if violations:
        lines.extend(["### Violations", ""])
        for item in violations:
            policy_status = _policy_status_label(item.get("policy_status"))
            policy_detail = f" [Policy status: {policy_status}]" if policy_status else ""
            lines.append(
                f"- {item.get('severity', 'low')}: "
                f"{item.get('message', '')}{policy_detail}"
            )
        lines.append("")
    if warnings:
        lines.extend(["### Warnings", ""])
        for item in warnings:
            policy_status = _policy_status_label(item.get("policy_status"))
            policy_detail = f" [Policy status: {policy_status}]" if policy_status else ""
            lines.append(
                f"- {item.get('severity', 'low')}: "
                f"{item.get('message', '')}{policy_detail}"
            )
        lines.append("")
    if not violations and not warnings:
        lines.extend(["No policy violations or warnings detected.", ""])
    return lines


def _risk_section(risks: list[dict[str, str]]) -> list[str]:
    lines = ["## Risks", ""]
    lines.extend([SECTION_DESCRIPTIONS["Risks"], ""])
    if not risks:
        lines.extend(["None detected.", ""])
        return lines
    for risk in risks:
        lines.append(f"- {risk['severity']}: {risk['reason']}")
    lines.append("")
    return lines


def _list(value: Any) -> list[Any]:
    return value if isinstance(value, list) else []


def _finding_list(value: Any) -> list[dict[str, Any]]:
    if not isinstance(value, list):
        return []
    return [item for item in value if isinstance(item, dict)]


def _policy_review_status(policy_review: dict[str, Any]) -> str:
    if _finding_list(policy_review.get("violations")):
        return "failed"
    if _finding_list(policy_review.get("warnings")):
        return "passed with warnings"
    return "passed"


def _policy_status_label(value: object) -> str:
    labels = {
        "undocumented": "undocumented",
        "documented_by_repository_policy": "documented by repository policy",
        "policy_warning": "policy warning",
        "policy_violation": "policy violation",
        "not_applicable": "not applicable",
    }
    return labels.get(str(value), "")
